#include "rwmake.ch"
#include "protheus.ch"

/*/

———————————————————————————————————————————————————————————————————————————————
@function		MT140PC                                                        /@
@date		   	21/09/2015                                                        /@
@type		    	Ponto de entrada                                                  /@
@description	Este Ponto de Entrada tem por objetivo manipular o parâmetro   /@
					MV_PCNFE utilizado na Pré Nota de Entrada a ser gerada         /@
@author			Felipe Varella ( Brasitech                                     /@
@use		    	Específico Brasitech                                              /@
———————————————————————————————————————————————————————————————————————————————


/*/

User Function MT140PC() 
Local lret 	:= .F.
Return lret
