#Include "Rwmake.ch"
#include "topconn.ch"  
#include "TOTVS.CH"
/*_____________________________________________________________________________
¦ Função    ¦ MA651PRCLocal ¦ Autor ¦ Ricky Moraes          ¦ Data ¦ 29-05-19 ¦
+-----------+------------+-------+------------------------+------+------------+
¦ Descriçäo ¦  Marcação da Ordem de Produção 								¦
 ¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯ */
 

User Function M651DPC()

Local lRet := .T. 
	//alert('1')

return(lRet) 
